### ISSUE TITLE
Postgresql 12 upgrade

### ISSUE THREAD

**Issue by andysodt** [seattleflu/id3c#152]
Hi!

I have some free time this week and would like to attempt upgrading postgresql.

Is this a good idea and time to do this?

Also, should I go for postgresql 12?

**Comment by kairstenfay** [comment]
Hi @andysodt. Thanks for reaching out. If the PostgreSQL upgrade is something you're interested in, then by all means feel free to work on it. 

@tsibley mentioned the other day that PostgreSQL 12 has some additional features we could use in id3c, but I don't know if he specified what those were.

**Comment by tsibley** [comment]
Hi @andysodt, sorry we didn't see this until after the weekend. :-/

I think it'd be great to test an upgrade to Pg 12. The improvements in Pg 11 and 12's support for JSON data types, parallel queries, and generated columns are all things that'd be nice to have. I think the biggest unknown is what, if anything, needs updating in ID3C to account for backwards incompatible changes made between Pg 10 → 12. Since we don't have a comprehensive test suite that can exercise the codebase, I think working on the upgrade will mean a combination of a) trying out 12 and seeing if anything pops up and b) auditing the code for usage of backwards incompatible features as documented by Pg's release notes. A bit of our production code is also wrapped up in https://github.com/seattleflu/id3c-customizations, which would also need to be validated/audited in order for us to do an upgrade in production, but core ID3C is the first step here.

If you're still interested, please jump in. :-) Let us know if you have questions or comments and we'll try to help.

**Comment by andysodt** [comment]
Ok thanks!  I May have some extra time to look at this on Monday.  I have been a bit busy with work lately and have not been up on github much.

**Comment by andysodt** [comment]
Is there anywhere in the config code that specified what db is required?  I couldn't find anything.  Just install 12 and try out, correct?

**Comment by tsibley** [comment]
Of course, no worries!
