### ISSUE TITLE
Cannot run `sqitch revert` past `warehouse/organism`

### ISSUE THREAD

**Issue by kairstenfay** [seattleflu/id3c#41]
When running `sqitch revert` on a recent copy of the `seattleflu` db from production, I get the following error:
```
Change "warehouse/target/organism @2019-07-12" required by currently deployed change: seattleflu/id3c-customizations:warehouse/target/data
```
Truncating `warehouse.organism` produces this error:
```
seattleflu=# truncate warehouse.organism;
ERROR:  cannot truncate a table referenced in a foreign key constraint
DETAIL:  Table "target" references "organism".
HINT:  Truncate table "target" at the same time, or use TRUNCATE ... CASCADE.
```

Running `sqitch revert warehouse/kit` works, though.

**Comment by tsibley** [comment]
This is by design. What the first error message means is that the sqitch project in seattleflu/id3c-customizations has a change (adding our organism data) which relies on the ID3C sqitch change `warehouse/target/organism`. If you revert the id3c-customizations change first, then you can revert past `warehouse/target/organism`. In general though, I find that doing large sqitch reverts in dev is usually unnecessary once a change has been deployed to production. Happy to discuss this in more detail in person when you're back (or via video before then).
